require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AmbassadorsController do

  # This should return the minimal set of attributes required to create a valid
  # Ambassador. As you add validations to Ambassador, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AmbassadorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ambassadors as @ambassadors" do
      ambassador = Ambassador.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ambassadors)).to eq([ambassador])
    end
  end

  describe "GET show" do
    it "assigns the requested ambassador as @ambassador" do
      ambassador = Ambassador.create! valid_attributes
      get :show, {:id => ambassador.to_param}, valid_session
      expect(assigns(:ambassador)).to eq(ambassador)
    end
  end

  describe "GET new" do
    it "assigns a new ambassador as @ambassador" do
      get :new, {}, valid_session
      expect(assigns(:ambassador)).to be_a_new(Ambassador)
    end
  end

  describe "GET edit" do
    it "assigns the requested ambassador as @ambassador" do
      ambassador = Ambassador.create! valid_attributes
      get :edit, {:id => ambassador.to_param}, valid_session
      expect(assigns(:ambassador)).to eq(ambassador)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ambassador" do
        expect {
          post :create, {:ambassador => valid_attributes}, valid_session
        }.to change(Ambassador, :count).by(1)
      end

      it "assigns a newly created ambassador as @ambassador" do
        post :create, {:ambassador => valid_attributes}, valid_session
        expect(assigns(:ambassador)).to be_a(Ambassador)
        expect(assigns(:ambassador)).to be_persisted
      end

      it "redirects to the created ambassador" do
        post :create, {:ambassador => valid_attributes}, valid_session
        expect(response).to redirect_to(Ambassador.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ambassador as @ambassador" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ambassador.any_instance.stub(:save).and_return(false)
        post :create, {:ambassador => { "name" => "invalid value" }}, valid_session
        expect(assigns(:ambassador)).to be_a_new(Ambassador)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ambassador.any_instance.stub(:save).and_return(false)
        post :create, {:ambassador => { "name" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ambassador" do
        ambassador = Ambassador.create! valid_attributes
        # Assuming there are no other ambassadors in the database, this
        # specifies that the Ambassador created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Ambassador).to receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => ambassador.to_param, :ambassador => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested ambassador as @ambassador" do
        ambassador = Ambassador.create! valid_attributes
        put :update, {:id => ambassador.to_param, :ambassador => valid_attributes}, valid_session
        expect(assigns(:ambassador)).to eq(ambassador)
      end

      it "redirects to the ambassador" do
        ambassador = Ambassador.create! valid_attributes
        put :update, {:id => ambassador.to_param, :ambassador => valid_attributes}, valid_session
        expect(response).to redirect_to(ambassador)
      end
    end

    describe "with invalid params" do
      it "assigns the ambassador as @ambassador" do
        ambassador = Ambassador.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ambassador.any_instance.stub(:save).and_return(false)
        put :update, {:id => ambassador.to_param, :ambassador => { "name" => "invalid value" }}, valid_session
        expect(assigns(:ambassador)).to eq(ambassador)
      end

      it "re-renders the 'edit' template" do
        ambassador = Ambassador.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ambassador.any_instance.stub(:save).and_return(false)
        put :update, {:id => ambassador.to_param, :ambassador => { "name" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ambassador" do
      ambassador = Ambassador.create! valid_attributes
      expect {
        delete :destroy, {:id => ambassador.to_param}, valid_session
      }.to change(Ambassador, :count).by(-1)
    end

    it "redirects to the ambassadors list" do
      ambassador = Ambassador.create! valid_attributes
      delete :destroy, {:id => ambassador.to_param}, valid_session
      expect(response).to redirect_to(ambassadors_url)
    end
  end

end
